"""empty message

Revision ID: 65bf354ae3a0
Revises: e705519cefef
Create Date: 2021-02-14 19:15:16.504730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65bf354ae3a0'
down_revision = 'e705519cefef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'test_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('test_col', mysql.VARCHAR(length=49), nullable=True))
    # ### end Alembic commands ###
