"""empty message

Revision ID: e705519cefef
Revises: 
Create Date: 2021-02-14 19:14:37.233691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e705519cefef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('test_col', sa.String(length=49), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'test_col')
    # ### end Alembic commands ###
